# Generated by Django 3.2 on 2021-04-28 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210427_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date_published',
        ),
    ]
