# Generated by Django 3.2 on 2021-04-28 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quiz_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='ends_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='starts_at',
            field=models.DateField(),
        ),
    ]
