# Generated by Django 3.2 on 2021-05-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210428_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenquiz',
            name='obtained_marks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
