# Generated by Django 3.2 on 2021-05-03 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210501_0506'),
        ('quiz', '0006_takenquiz_obtained_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='taken_quiz',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='accounts.studentprofile'),
        ),
    ]
