# Generated by Django 5.2.3 on 2025-06-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_is_public_classroom_quiz_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='starts_at',
        ),
    ]
