# Generated by Django 3.2 on 2021-04-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(default='utility_images/default_image.png', upload_to='profile_images/students_profile_images/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='facebook_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='instagram_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='utility_images/default_image.png', null=True, upload_to='profile_images/teachers_profile_images/'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='twitter_profile',
            field=models.URLField(blank=True, null=True),
        ),
    ]
