# Generated by Django 3.2 on 2021-05-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_studentprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='utility_images/default_image.png', null=True, upload_to='profile_images/teachers_profile_images/'),
        ),
    ]
